-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 23, 2021 at 08:04 AM
-- Server version: 10.4.17-MariaDB
-- PHP Version: 7.3.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `shop_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin_accounts`
--

CREATE TABLE `admin_accounts` (
  `Id` int(11) NOT NULL,
  `username` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  `name` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `admin_accounts`
--

INSERT INTO `admin_accounts` (`Id`, `username`, `password`, `name`) VALUES
(1, 'juan', 'password', 'juan delacruz');

-- --------------------------------------------------------

--
-- Table structure for table `cart`
--

CREATE TABLE `cart` (
  `guestName` varchar(100) NOT NULL,
  `Name` varchar(100) NOT NULL,
  `Price` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `cart`
--

INSERT INTO `cart` (`guestName`, `Name`, `Price`) VALUES
('juan', 'GPU', '20000.00');

-- --------------------------------------------------------

--
-- Table structure for table `guest`
--

CREATE TABLE `guest` (
  `Name` varchar(100) NOT NULL,
  `Email` varchar(100) NOT NULL,
  `Contact_Number` varchar(100) NOT NULL,
  `Address` varchar(100) NOT NULL,
  `City` varchar(100) NOT NULL,
  `State_Province` varchar(100) NOT NULL,
  `Postal_Zip_Code` varchar(100) NOT NULL,
  `Created_At` varchar(100) NOT NULL,
  `Updated_At` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Table structure for table `product`
--

CREATE TABLE `product` (
  `Name` varchar(100) NOT NULL,
  `Short_description` varchar(500) NOT NULL,
  `Price` varchar(100) NOT NULL,
  `Status` varchar(100) NOT NULL,
  `Created_At` varchar(100) NOT NULL,
  `Updated_At` varchar(100) NOT NULL,
  `Deleted_At` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `product`
--

INSERT INTO `product` (`Name`, `Short_description`, `Price`, `Status`, `Created_At`, `Updated_At`, `Deleted_At`) VALUES
('apple watch', 'a wearable smartwatch that allows users to accomplish a variety of tasks', '9000.00', 'Active', '03-22-21', '03/23/2021', '03/23/2021'),
('charger cable', 'a cable used to charge a smartphone or other portable device', '250.00', 'In-Active', '03-21-21', '03/23/2021', '03/23/2021'),
('GPU', 'a chip or electronic circuit capable of rendering graphics for display on an electronic device', '20000.00', 'Active', '03-22-21', 'N/A', 'N/A'),
('headset', 'a hardware device that connects to a telephone or computer, allowing the user to talk and listen while keeping their hands free', '1000.00', 'In-Active', '03-22-21', 'N/A', '03/23/2021'),
('keyboard', 'a input device that allows a person to enter letters, numbers, and other symbols', '600.00', 'In-Active', '03-21-21', 'N/A', '03-22-21'),
('lan cable', 'connects to computers, network switches and then from the switch to a router, modem', '200.00', 'Active', '03/23/2021', 'N/A', 'N/A'),
('monitor', 'displays the video and graphics information generated by a connected computer through the computers video card', '6000.00', 'Active', '03-22-21', 'N/A', 'N/A'),
('mouse', 'a small handheld input device that controls a computer screens cursor or pointer', '600.00', 'Active', '03-22-21', 'N/A', 'N/A'),
('proccessor', 'a integrated electronic circuit that performs the calculations that run a computer.', '5000.00', 'Active', '03-21-21', 'N/A', 'N/A'),
('RAM', 'a computing device where the operating system (OS), application programs and data in current use are kept', '3000.00', 'Active', '03-22-21', 'N/A', 'N/A'),
('smart phone', 'a handheld electronic device that provides a connection to a cellular network', '20000.00', 'Active', '03-22-21', 'N/A', 'N/A'),
('speaker', 'a one of the most common output devices used with computer systems', '1000.00', 'Active', '03-22-21', 'N/A', 'N/A'),
('webcam', 'a video camera that feeds or streams an image or video in real time to or through a computer to a computer network', '900.00', 'Active', '03-22-21', 'N/A', 'N/A'),
('wifi dungle', 'Wi-Fi USB sticks that can connect to laptops, smart phones, or tablets to provide them with convenient internet service on the go', '600.00', 'Active', '03/23/2021', 'N/A', 'N/A'),
('wifi router', 'a networking device allowing for several internet devices to be connected to the same internet gateway', '100.00', 'Active', '03-21-21', 'N/A', 'N/A'),
('wireless charger', 'known as Inductive Charging, is a convenient and cable-free way to charge your electronic devices.', '500.00', 'Active', '03-22-21', 'N/A', 'N/A');

-- --------------------------------------------------------

--
-- Table structure for table `product category`
--

CREATE TABLE `product category` (
  `Name` varchar(100) NOT NULL,
  `Created_At` varchar(100) NOT NULL,
  `Updated_At` varchar(100) NOT NULL,
  `Deleted_At` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `product category`
--

INSERT INTO `product category` (`Name`, `Created_At`, `Updated_At`, `Deleted_At`) VALUES
('apple watch', '03-22-21', 'N/A', 'N/A'),
('smart phone', '03-22-21', 'N/A', 'N/A'),
('wireless charger', '03-22-21', 'N/A', 'N/A');

-- --------------------------------------------------------

--
-- Table structure for table `todeliver`
--

CREATE TABLE `todeliver` (
  `Name` varchar(100) NOT NULL,
  `Email` varchar(100) NOT NULL,
  `Contact` varchar(100) NOT NULL,
  `Address` varchar(100) NOT NULL,
  `City` varchar(100) NOT NULL,
  `ItemName` varchar(100) NOT NULL,
  `Price` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin_accounts`
--
ALTER TABLE `admin_accounts`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`Name`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin_accounts`
--
ALTER TABLE `admin_accounts`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
